'use strict';

const { getUniversityKnowledge, normalise } = require('./universityKnowledge');
const { getWebsiteKnowledge, getRelevantWebsiteDocuments } = require('./websiteKnowledge');

const STRUCTURED_DATA_POLICY = 'QUY TẮC DỮ LIỆU: phải sử dụng cả BỘ NHỚ ĐÃ LƯU và DỮ LIỆU WEBSITE khi chúng bổ sung cho nhau. Nếu hai nguồn mâu thuẫn, ưu tiên nguồn có ngày cập nhật mới hơn và nói rõ chênh lệch; không âm thầm bỏ một nguồn. Ưu tiên các trường định lượng trong hồ sơ trường; giá trị null hoặc “chưa xác minh” phải được nói rõ, không suy diễn phân hạng visa, GPA, TOPIK, chi phí, chứng chỉ cố vấn hoặc case study.';

// Chuẩn hoá từ các tài liệu chương trình và FAQ do Sol Dream cung cấp (08/2026).
const articles = [
  { title: 'Thạc sĩ Hannam - Golf và Beauty/Make up', keywords: ['hannam thạc sĩ', 'thạc sĩ hannam', 'golf', 'beauty', 'make up', 'e-visa', 'visa điện tử', 'd2 hannam', 'học cao học'], text: `CHƯƠNG TRÌNH THẠC SĨ ĐẶC BIỆT ĐH HANNAM - GOLF & BEAUTY/MAKE UP: Hệ thạc sĩ visa D2 dạng visa điện tử; tài liệu ghi cấp trực tiếp từ Hàn Quốc. Trường ở Daejeon; nhập học tháng 3/9, học 4 kỳ (2 năm), trung bình 1 buổi/tuần tùy khoa. Tốt nghiệp: đủ 30 tín chỉ trong 4 kỳ hoặc 24 tín chỉ và thi tốt nghiệp. Điều kiện: đã tốt nghiệp đại học; tài liệu ghi nhận hồ sơ đến năm sinh 1990; TOPIK 2 được ưu tiên xét tuyển thẳng. Chưa có TOPIK có thể nợ TOPIK và học tiếng Hàn online cùng Hannam để xét đầu vào. Hồ sơ: hộ chiếu; bằng/bảng điểm đại học dịch thuật-hợp pháp hóa lãnh sự; 2 ảnh 3.5x4.5; CCCD học sinh/bố/mẹ; giấy khai sinh; xác nhận cư trú có bố mẹ/học sinh; TOPIK nếu có; chứng minh thu nhập; xác nhận số dư 8.000.000 KRW cấp trong 30 ngày; xét nghiệm lao trong 3 tháng. Tài liệu có tiêu đề kỳ 03/2027 nhưng lịch nội dung là 2026, vì vậy phải xác nhận với tư vấn viên về kỳ tuyển sinh, hạn hồ sơ, học phí và lịch phỏng vấn hiện tại.` },
  { title: 'Danh mục các trường đại học Hàn Quốc', keywords: ['trường đại học', 'các trường', 'trường hàn', 'đại học hàn quốc', 'chọn trường', 'yonsei', 'sejong', 'gachon', 'hannam', 'woosong', 'hanyang', 'daejeon university', 'mokwon', 'konyang', 'daeduk', 'suncheon', 'wonkwang', 'cheongju', 'kunsan', 'dongyang', 'dongeui', 'gimhae', 'gangwon university', 'kyung hee'], text: `DANH MỤC TRƯỜNG TRONG CÁC TÀI LIỆU: Yonsei, Sejong, Gachon, Hannam, Woosong, Hanyang, Daejeon University, Mokwon, Konyang, Daeduk, Sunchon National, Wonkwang, Cheongju, Kunsan National, Dongyang, Dongeui, Gimhae College, Gangwon National và Kyung Hee. Chatbot có hồ sơ chi tiết theo từng mục (tổng quan, chương trình/ngành, học phí, học bổng và ký túc xá) cho Hannam, Woosong, Hanyang, Daeduk, Dongyang và Gimhae. Hầu hết hệ tiếng khai giảng tháng 3/6/9/12; chuyên ngành thường tháng 3/9 (Daeduk và Gimhae hệ tiếng tháng 3/9; chuyên ngành Gimhae trong tài liệu ghi tháng 3). Yonsei thuộc nhóm SKY, mạnh kinh tế-quản trị, y-dược, kỹ thuật, ngoại ngữ; tiếng Hàn khoảng 1,77 triệu KRW/kỳ. Sejong ở Seoul, mạnh du lịch-khách sạn, nghệ thuật, CNTT/hoạt hình; tiếng Hàn 1,6 triệu KRW/kỳ. Gachon gần Seoul, mạnh y-dược, y sinh, CNTT, thiết kế; tiếng Hàn 1,3 triệu KRW/kỳ. Hannam ở Daejeon mạnh kinh doanh, ngôn ngữ, thiết kế, CNTT, sinh học; tiếng Hàn 1,3 triệu KRW/kỳ. Woosong ở Daejeon có SolBridge/Endicott, mạnh kinh doanh quốc tế, khách sạn-ẩm thực, CNTT; tiếng Hàn 1,2 triệu KRW/kỳ. Hanyang có campus Seoul và ERICA, nổi bật về kỹ thuật, công nghệ, kiến trúc và kinh doanh; học tiếng khoảng 1,8 triệu KRW/kỳ tại Seoul hoặc 1,36-1,4 triệu KRW/kỳ tại ERICA. Daejeon University mạnh Đông y, điều dưỡng, y tế, thiết kế, kinh doanh; tiếng Hàn 1,2 triệu KRW/kỳ. Mokwon mạnh nghệ thuật, âm nhạc, thiết kế, sư phạm; tiếng Hàn 1,2 triệu KRW/kỳ. Konyang mạnh y khoa, điều dưỡng, công nghệ y tế, kinh doanh; tiếng Hàn 1,025 triệu KRW/kỳ. Daeduk định hướng thực hành, mạnh kỹ thuật, điều dưỡng, làm đẹp-thời trang, hàng không; tiếng Hàn 1,225 triệu KRW/kỳ. Sunchon, Kunsan và Gangwon National là nhóm trường quốc lập có kỹ thuật, nông-sinh học/biển, kinh doanh-ngôn ngữ. Dongyang mạnh đường sắt/kỹ thuật, CNTT-thiết kế; Dongeui mạnh y tế, kỹ thuật, du lịch-kinh doanh; Gimhae College mạnh y tế-chăm sóc sức khỏe, kỹ thuật-dịch vụ; Wonkwang và Kyung Hee có thế mạnh y-dược. Học phí/KTX, ngành mở tuyển, học bổng và kỳ tuyển sinh thay đổi theo năm/khoa; cần xác nhận trước khi đăng ký.` },
  { title: 'Danh mục chương trình du học hiện có', keywords: ['chương trình', 'các chương trình', 'du học', 'chương trình du học', 'có những chương trình', 'tư vấn du học'], text: `Khi người dùng hỏi tổng quan về các chương trình du học, hãy liệt kê ĐỦ 4 chương trình sau, mỗi chương trình 1 dòng ngắn, không tự thêm chương trình khác: (1) D2-1 hệ Cao đẳng nghề tổng quát; (2) D2-1 Cao đẳng tỉnh lập Gangwon - định hướng tối ưu chi phí, tài liệu nêu miễn học phí 2 năm; (3) D2-6 trao đổi CĐ Bách khoa Sài Gòn & Daeduk - định hướng vừa học vừa thực tập; (4) D4-1 & D2-2 Đại học Dongyang - học tiếng 6 tháng, sau đó học Kỹ thuật hạ tầng đường sắt quốc tế. Kết thúc bằng câu hỏi người dùng quan tâm chương trình nào để tư vấn điều kiện và chi phí chi tiết.` },
  { title: 'FAQ - Điều kiện, TOPIK và lộ trình', keywords: ['điều kiện', 'topik', 'bằng tiếng', 'chưa biết tiếng', 'lộ trình', 'đại học', 'gpa', 'tuổi', 'sức khỏe', 'hồ sơ', 'quy trình', 'visa'], text: `Điều kiện FAQ: tốt nghiệp THPT/đại học; thời gian trống thường không quá 2-3 năm; GPA từ 6.5 trở lên. Một số trường Top 1% yêu cầu GPA từ 8.0 và số buổi nghỉ không quá 10. Tuổi tham khảo 18-25, sức khỏe tốt, không lao phổi/bệnh truyền nhiễm và không tiền án tiền sự. Chưa có TOPIK vẫn có thể đi hệ học tiếng D4-1; đạt tối thiểu TOPIK 3 mới học chuyên ngành/đại học hệ D2. Lộ trình 1: học tiếng tại VN 3-6 tháng, D4-1 tại Hàn 6-18 tháng lấy TOPIK 3/4 rồi lên đại học. Lộ trình 2: học tiếng tại VN 9-18 tháng lấy TOPIK 3/4 rồi đi thẳng D2. Quy trình: tư vấn chọn trường/học tiếng, nộp hồ sơ, phỏng vấn trường, nhận kết quả và đóng học phí, thư mời/visa, phỏng vấn LSQ nếu có, nhập cảnh. FAQ nêu trượt visa cần chờ 3 tháng mới nộp lại.` },
  { title: 'FAQ - Chi phí, làm thêm và học bổng', keywords: ['chi phí', 'học phí', 'bao nhiêu tiền', 'làm thêm', 'việc làm', 'lương', 'thu nhập', 'học bổng', 'thời gian làm'], text: `FAQ ước tính chi phí ban đầu tại Việt Nam và học phí năm đầu khoảng 150-300 triệu VNĐ, tùy trường, Seoul hay tỉnh. Hệ tiếng chưa có TOPIK được làm thêm sau 6 tháng; sinh viên đại học/thạc sĩ được làm thêm ngay. Thời gian tham khảo 20-25 giờ/tuần, không giới hạn trong kỳ nghỉ. Lương tham khảo 10.000-12.000 KRW/giờ (180.000-230.000 VNĐ/giờ), thu nhập bình quân 15-25 triệu VNĐ/tháng. Học bổng TOPIK 3-6 có thể giảm 30%-100% học phí kỳ đầu, hoặc dựa GPA xuất sắc. Các số liệu/quy định cần tư vấn viên xác nhận tại thời điểm đăng ký.` },
  { title: 'D2-1 - Cao đẳng nghề tổng quát', keywords: ['d2-1', 'cao đẳng nghề', 'cao đẳng', 'ngành học', 'liên thông', 'e7', 'f2-r', 'tháng 3', 'tháng 9'], text: `Hệ cao đẳng nghề D2-1: nhập học tháng 3 hoặc 9; áp dụng hầu hết cao đẳng tại Hàn, trừ các chương trình riêng Daeduk, Woosong, Gangwon. Điều kiện: tốt nghiệp THPT/trung cấp/cao đẳng, thời gian trống không quá 2 năm. Chuẩn bị tại VN 3-6 tháng; học tiếng/văn hóa để TOPIK 2 trước khi đi (tài liệu ghi 4-8 tháng). Mỗi năm 2 kỳ, mỗi kỳ khoảng 3.5 tháng; tuần học 1-2 ngày trường và 1 ngày online. Có thể liên thông đại học. Ngành: ngôn ngữ Hàn, ô tô, cơ khí, điện-điện tử, thiết kế công nghiệp, điều dưỡng, làm bánh, quản trị kinh doanh, du lịch-khách sạn, làm đẹp, phúc lợi xã hội. Học phí chuyên ngành tham khảo 2.533.500 KRW/kỳ (xã hội-dịch vụ) đến 4.513.000 KRW/kỳ (kỹ thuật). Chi phí tại Sol Dream: liên hệ tư vấn. Tài liệu ghi lương cơ bản 2026 từ 10.320 KRW/giờ và được làm thêm sau 1 tháng có thẻ cư trú; phải xác nhận lại quy định hiện hành.` },
  { title: 'D2-1 - Cao đẳng tỉnh lập Gangwon', keywords: ['gangwon', 'gangneung', 'miền bắc', 'd2-1', 'cao đẳng tỉnh lập', 'miễn học phí', 'drone', 'barista', 'du lịch', '180 triệu'], text: `CĐ tỉnh lập Gangwon ở Gangneung, nhập học tháng 3/9; điều kiện tốt nghiệp THPT/trung cấp/cao đẳng, thời gian trống không quá 2 năm. Học TOPIK 2/văn hóa Hàn tại VN 4-8 tháng. Điểm nổi bật tài liệu: miễn toàn bộ học phí 2 năm tại Hàn. Tổng chi phí tài liệu miền Bắc: 180 triệu VNĐ, gồm học tiếng TOPIK 2/văn hóa, hồ sơ visa, 1 vé khứ hồi nội địa, học phí kỳ đầu (trường hoàn lại sau nhập học), KTX 6 tháng, phí đăng ký/nhập học. Không gồm sinh hoạt VN, chứng minh tài chính, bảo hiểm quốc dân (tài liệu khoảng 1,5 triệu VNĐ/tháng). Thanh toán: 35 triệu, 50 triệu, 70 triệu, phần còn lại sau visa. Ngành: du lịch-khách sạn, xây dựng dân dụng, thủy hải sản, drone, barista/bánh, kỹ thuật hàng hải. Chi phí sinh hoạt theo tài liệu thấp hơn Seoul 20-30%; KTX từ Seoul khoảng 2 giờ. Làm thêm ít hơn Seoul, cần chủ động.` },
  { title: 'D2-6 - Cao đẳng Bách khoa Sài Gòn và Daeduk', keywords: ['d2-6', 'daeduk', 'daejeon', 'bách khoa sài gòn', 'thực tập', '300 triệu', '280 doanh nghiệp', 'e7', 'f2-r'], text: `Trao đổi D2-6 CĐ Bách khoa Sài Gòn & Daeduk: nhập học tháng 3/9; điều kiện tốt nghiệp THPT/trung cấp/cao đẳng, thời gian trống không quá 2 năm. Chuẩn bị VN 3-6 tháng, tại Hàn tối thiểu 2,5 năm. Học tiếng/văn hóa tại VN 4-8 tháng. Từ kỳ 2 tại Hàn, chuyên ngành 1-2 buổi/tuần; có thể thực tập lương từ kỳ 3 nếu TOPIK 2 hoặc kỳ 4. Tài liệu nêu mức lương tối thiểu khoảng 40 triệu VNĐ/tháng chưa tăng ca, liên kết việc làm Daejeon và hơn 280 doanh nghiệp, hỗ trợ E7/F2-R sau tốt nghiệp. Việc làm 100% chỉ nêu cho học sinh đủ điều kiện tốt nghiệp. Tổng chi phí: 300 triệu VNĐ, gồm hồ sơ, học CĐ Bách khoa, tiếng Hàn, vé máy bay, học phí kỳ 1-2, KTX 3 tháng có bữa sáng/tối, phí đăng ký/nhập học. Không gồm sinh hoạt cá nhân, ăn/KTX VN, chứng minh tài chính. Thanh toán: 35 triệu, 50 triệu, 150 triệu, phần còn lại sau visa. Daeduk ở Daejeon, cách Seoul khoảng 1 giờ tàu; hợp người muốn sớm tự lập nhưng áp lực vừa học vừa làm.` },
  { title: 'D4-1 và D2-2 - Đại học Dongyang', keywords: ['dongyang', 'd4-1', 'd2-2', 'đường sắt', 'yeongju', 'dongducheon', '180 triệu', '6 tháng', 'top 3'], text: `Đại học Dongyang 2026-2027: học tiếng 6 tháng rồi lên chuyên ngành. Campus tiếng ở Yeongju (Gyeongsangbuk), chuyên ngành ở Dongducheon (Gyeonggi). Điều kiện: tốt nghiệp THPT/TC/CĐ/ĐH, thời gian trống không quá 2 năm. Visa D4-1; nhập học tháng 3,6,9,12; hạn nộp hồ sơ tham khảo: 15/11, 15/03, 15/06, 15/08. Tổng chi phí tài liệu: 180 triệu VNĐ, gồm lớp tiếng online 2 tháng, hồ sơ/thư mời/hợp pháp hóa/visa/khám sức khỏe, học phí tiếng 6 tháng, phí nhập học, KTX 6 tháng. Không gồm sổ đóng băng Woori 8 triệu KRW, ăn/KTX VN, bảo hiểm Hàn. Thanh toán: 35 triệu, 120 triệu, 25 triệu sau visa. Chuyên ngành Kỹ thuật hạ tầng đường sắt quốc tế, học phí 2,5 triệu KRW/kỳ (~47 triệu VNĐ); học chuyên ngành 3 ngày/tuần. Lớp tiếng thứ 2-6, 10 tuần/kỳ, 9:00-13:00. Làm thêm hệ tiếng sau 6 tháng theo tài liệu; phải xác nhận lại quy định.` }
];

function getRelevantKnowledge(question, options = {}) {
  const query = normalise(question);
  const universityKnowledge = getUniversityKnowledge(question);
  const websiteKnowledge = getWebsiteKnowledge(question, {
    maxChars: options.maxWebsiteChars || 16000,
    maxDocuments: options.maxDocuments || 10,
  });
  const bestWebsiteMatch = getRelevantWebsiteDocuments(question, { maxDocuments: 1 })[0];
  const memoryBlock = (text) => `BỘ NHỚ KIẾN THỨC ĐÃ LƯU TRƯỚC ĐÂY (từ tài liệu trường, chương trình và FAQ do SOL DREAM EDUCATION cung cấp):\n${text}`;
  const mergeSources = (memory, preferWebsite = false) => [
    ...(preferWebsite ? [websiteKnowledge, memoryBlock(memory)] : [memoryBlock(memory), websiteKnowledge]),
    STRUCTURED_DATA_POLICY,
  ].join('\n\n');
  const asksAboutAllProgrammeCosts = ['hoc phi', 'chi phi', 'bao nhieu tien', 'tong chi phi'].some((term) => query.includes(term))
    && ['chuong trinh', 'du hoc', 'cac he'].some((term) => query.includes(term));
  if (asksAboutAllProgrammeCosts && !universityKnowledge) {
    const programmeCosts = articles
      .filter((article) => ['D2-1 - Cao đẳng nghề tổng quát', 'D2-1 - Cao đẳng tỉnh lập Gangwon', 'D2-6 - Cao đẳng Bách khoa Sài Gòn và Daeduk', 'D4-1 và D2-2 - Đại học Dongyang'].includes(article.title))
      .map((article) => `### ${article.title}\n${article.text}`)
      .join('\n\n');
    return mergeSources(programmeCosts);
  }
  const scoredMatches = articles.map((article) => ({
    article,
    score: article.keywords.reduce((total, keyword) => {
      const found = query.includes(normalise(keyword));
      const isProgrammeName = ['gangwon', 'gangneung', 'daeduk', 'daejeon', 'dongyang', 'yeongju', 'dongducheon', 'd2-1', 'd2-6', 'd4-1', 'd2-2'].includes(normalise(keyword));
      return total + (found ? (isProgrammeName ? 4 : 1) : 0);
    }, 0)
  }))
    .filter(({ score }) => score).sort((a, b) => b.score - a.score).slice(0, 2);
  const matched = scoredMatches.map(({ article }) => article);
  if (universityKnowledge) {
    const supportingArticles = scoredMatches
      .filter(({ article, score }) => score >= 2 && article.title !== 'Danh mục các trường đại học Hàn Quốc')
      .slice(0, 1)
      .map(({ article }) => article);
    const storedMemory = [universityKnowledge, ...supportingArticles.map((article) => `### ${article.title}\n${article.text}`)].join('\n\n');
    return mergeSources(storedMemory);
  }
  const referenceKnowledge = matched.length
    ? matched.map((article) => `### ${article.title}\n${article.text}`).join('\n\n')
    : 'Bộ nhớ đã lưu không có mục nào khớp chắc chắn với câu hỏi hiện tại. Không được lấy một chương trình hoặc trường bất kỳ để thay thế; chỉ sử dụng dữ liệu website truy xuất được và hỏi làm rõ nếu vẫn thiếu thông tin.';
  const websiteHasExactContent = bestWebsiteMatch && bestWebsiteMatch.score >= 35 && ['program', 'post', 'course'].includes(bestWebsiteMatch.type);
  return mergeSources(referenceKnowledge, websiteHasExactContent);
}

module.exports = { getRelevantKnowledge, STRUCTURED_DATA_POLICY };
